### ISSUE TITLE
Bye

### ISSUE THREAD

**Issue by MaggieLOL** [ReDuowanmcbox/Reduowanmcbox-Server#3]
我将退出这个开发计划 你无权保留我的代码 我的所有代码许可证皆为AGPL-3，使用需要许可，当然你没有许可

**Comment by MaggieLOL** [comment]
保留的后果你也知道 那我就举报你github账号滥用呗/shrug

**Comment by NotFlyLoongQaQ** [comment]
当然了，没有人声明代码许可证是AGPL-3 :)

**Comment by NotFlyLoongQaQ** [comment]
当然，没人喜欢使用Loser的代码，已删除。
